### PR TITLE
[WIP] Port of DOP853

### PR DESCRIPTION
**Pull request by helgee**
This is an almost complete port of DOP853 (the dense output functionality is still missing) with quite good performance (https://groups.google.com/forum/#!searchin/julia-users/dop853/julia-users/41B3qULjF-0/WqGa-Lc04AkJ), approximately 2-3x slower than Fortran (without compiler optimizations) for longer runs. Since the 5-th order version DOPRI5 looks rather similar implementing it as well should not be a huge amount of work

See also: #25

To Do:
* [ ] API adjustment
* [ ] Dense output
* [X] DOPRI5
* [X] Write tests
* [ ] Documentation

* What else?
* Is it a good idea to separate different solver families in different source files?

### CODE REVIEW

**Comment by helgee** [comment]
I apologize for letting this PR go stale. Should I continue with this or would it make more sense to just add the 8th-order Dormand-Prince coefficients to the new Runge-Kutta solvers?

In that case I would still need facilities for event detection (e.g. a user function that gets called after every integration step and dense output) for ODE.jl to be useful to me. But until that is available I will use my wrapper for the Fortran codes (https://github.com/helgee/Dopri.jl).

**Comment by tlycken** [comment]
Adding the 8th-order coefficients would definitely be a nice contribution regardless of other things.

I personally hope that event detection can be handled with the approach outlined in #49, with support across all solvers in ODE.jl, but that's quite a large undertaking. Also, I don't have the opportunity to use ODE.jl regularly anymore - and thus my ability to invest time in it is also limited - so my opinion on the matter carries very little weight nowadays :)

**Comment by acroy** [comment]
I think we should stick to the current implementation for anything related to (explicit) RK methods. If you could add the 8th order coefficients this would be great.

If you have ideas or needs for event functions, please post them in #11.

**Comment by helgee** [comment]
Alright. I will close this then.

**Comment by mauro3** [comment]
It is easy to add the method to the existing RK solvers, you just need to provide a tableau like:
https://github.com/JuliaLang/ODE.jl/blob/01620ad46321b2088f4b90be1099b903c43dd788/src/runge_kutta.jl#L135

At the moment dense output is only 3rd order. To change that would require some code changes.  I hope to implement a general scheme at some point but cannot promise a time frame.  Same goes for event location.

**Pull request closed without merging**
