### PR TITLE
Enable precompilation

### PR DESCRIPTION
**Pull request by jgoldfar**

### CODE REVIEW

**Comment by ViralBShah** [comment]
@tkelman Is this still the preferred way to do the precompliation?

**Comment by tkelman** [comment]
Either this or `isdefined(Base, :__precompile__)`

Using `isdefined` has the benefit that it would work on `NO_GIT` builds of older 0.4-dev where version numbers are not accurate, but that's probably a rare case.

**Comment by acroy** [comment]
Certainly nice to have! I don't have a strong preference, which version we should use, but Tony's looks more elegant ...

**Comment by jgoldfar** [comment]
Good to know; I'll update the PR. I would note that Compat.jl does it this way, so it may be worth updating that as well

**Comment by tlycken** [comment]
`isdefined` has the added benefit of being *forwards* compatible, in case the mechanism for precompilation is changed in a future version of Julia (at least in the sense that nothing will throw errors; precompilation will silently break, but that won't make the package unusable).

**Comment by jgoldfar** [comment]
Test for when to enable precompilation is now updated.

**Pull request merged**
