### PR TITLE
WIP: Make coefficients Rational for better generics

### PR DESCRIPTION
**Pull request by tlycken**
*This is still just WIP, but I need some advice to keep this moving.*

@pwl [mentioned](https://github.com/JuliaLang/ODE.jl/pull/59#issuecomment-86431612) that it might be a good idea to convert all the coefficients in this code to rational, to make generic programming easier. I agree, since `Float64` is quite poisonous in this aspect; the promotion of almost anything and a `Float64` will be a `Float64`. We've [discussed before](https://github.com/JuliaLang/ODE.jl/issues/26) how to handle inputs of types that don't make sense in an ODE context and agreed that converting to floats is the most rational (heh...) thing to do, but there still might, for example, be applications for `Float32` arguments, or arguments of some user-defined number type, where we don't want to force `Float64`s on the user.

The PR currently only converts the coefficient tables that were already specified as fractions, but there is [one table that wasn't](https://github.com/JuliaLang/ODE.jl/blob/4a71fa0d97011aa4a35244e4685693bb99292e10/src/ODE.jl#L589-L598) (and I couldn't find a reference where it was) and there's also a bunch of coefficients and constants scattered throughout the various solvers, which are all specified as `Float64` literals. Do we want to try to make something more sensible with those? What?

It could also be argued that making the code generic yet type stable is too complicated to be worth the effort, in which case it's a good thing that I didn't spend more than a few minutes on this PR yet. (But I'd hate to end the discussion about this with "a `Float64` ought to be enough for anyone"...)

### CODE REVIEW

**Comment by tlycken** [comment]
(The build failures are because Coveralls doesn't work on 0.4 - all our tests pass on both versions...)

**Comment by mauro3** [comment]
The original paper by Kaps and Rentrop (1979) doesn't give ratios for the GRK4T coefficients, so presumably they are not know/don't exist.

**Comment by stevengj** [comment]
One problem is that conversion of constant rational coefficients to floating-point cannot be done at compile time, so we have to be cautious about using these in inner loops.

**Comment by mauro3** [comment]
Could/should `MathConst` be used instead?

Probably better convert the table before the inner loops to the used float-type.

**Comment by mauro3** [comment]
I think this has been addressed by #68, right?

**Comment by tlycken** [comment]
So it would seem.

**Pull request closed without merging**
