### PR TITLE
Added @acroy's test for custom scalar-like state

### PR DESCRIPTION
**Pull request by mauro3**
Also modified ode4 to use normal arithmetic, not `.*`-like

### CODE REVIEW

**Comment by mauro3** [comment]
Also, unrelated to the main part of the PR changed `copy` to `deepcopy` in ode23s.  I think that is more correct but I can take it out.

**Comment by acroy** [comment]
Thanks! This looks good. I am not 100% sure about `deepcopy` vs `copy`, but you are probably right. Do I get this right, that this test case doesn't work with `ode23s`? In that case we should have a new issue for fixing it.

**Comment by mauro3** [comment]
Yes, ode23s and the fixed step Rosenbock solvers use indexing and other bits. 

If you got a vector of mutables then a shallow copy will leave them the same, which might lead to problems?

Also, this is also part of #68.  If we merge that PR soon then we could close this and get it via 68.

**Comment by acroy** [comment]
> Yes, ode23s and the fixed step Rosenbock solvers use indexing and other bits.

The way the Jacobian is calculated prevents this (there is actually a "FIXME" comment for this - probably written by me :-).

> If you got a vector of mutables then a shallow copy will leave them the same, which might lead to problems?

Yes, it's better to use `deepcopy` then.

So from my side this can be merged.

**Comment by ViralBShah** [comment]
You guys know best when to merge.

**Comment by mauro3** [comment]
If PR #68 gets merged soon then I'd prefer to ditch this to save me some conflicts in rebasing #68.  Otherwise merge.

**Comment by mauro3** [comment]
Closing as the test was merged with #68

**Pull request closed without merging**
